"""Render the audit's evidence-indexed comparison; no inference/training/benchmark execution."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
REPO=ROOT.parent
PAPER='https://aclanthology.org/2025.acl-long.572.pdf'
TRL='https://github.com/hyc2026/trl/blob/7a266d8b4be2cbce2ae54082ac99ba97037bfd6b/'
E={}
def paper(key,loc,page): E[key]={'kind':'paper','version':'ACL 2025 final','location':loc,'url':PAPER+f'#page={page}','local_text':f'sources/acl_page_{page:02d}.txt'}
def code(key,file,start,end,function,training=False):
 E[key]={'kind':'training_code' if training else 'local_code','file':('sources/trl/' if training else '../')+file,'line_start':start,'line_end':end,'function':function,'url':TRL+file+f'#L{start}-L{end}' if training else f'{REPO/file}:{start}'}
for v in [('P_STATE','§4.2, printed pp.11666–11667; token-level MDP/state/functions',5),('P_FUN','Table 3 and Fig.2, p.11667; Search/Expand/Stop',5),('P_REWARD','§4.2 Eq.(1), p.11667',5),('P_RETURN','§4.2 Eq.(2)–(8), p.11668; session definition and return',6),('P_SETUP','§5.1–5.2, p.11669; Search, paper management, depth cap',7),('P_SFT','Appendix D.1, Tables 10–11, p.11675',13),('P_PPO','Appendix D.2, Table 12, p.11676',14),('P_COST','Appendix G.2, Table 15, p.11677',15),('P_GPT','Appendix H.2, Table 20, p.11679; GPT-4o baseline',17)]:paper(*v)
for v in [('C_RUN','paper_agent.py',234,237,'PaperAgent.run'),('C_INIT','paper_agent.py',30,71,'PaperAgent.__init__'),('C_SEARCH','paper_agent.py',132,136,'PaperAgent.search'),('C_SEARCH_PAPER','paper_agent.py',94,130,'PaperAgent.search_paper'),('C_CONTEXT','paper_agent.py',138,156,'PaperAgent.get_paper_content'),('C_REF','paper_agent.py',158,179,'PaperAgent.search_ref'),('C_DOEXP','paper_agent.py',181,221,'PaperAgent.do_expand'),('C_EXPAND','paper_agent.py',223,232,'PaperAgent.expand'),('C_INFER','models.py',47,72,'Agent.infer'),('C_BATCH','models.py',74,102,'Agent.batch_infer'),('C_SELECTOR','models.py',28,45,'Agent.infer_score'),('C_PROMPT','agent_prompt.json',1,6,'generate_query/select_section/get_selected'),('C_ENTRY','run_paper_agent.py',29,67,'entry point'),('C_NODE','paper_node.py',14,41,'PaperNode'),('C_GOOGLE','utils.py',44,81,'google_search_arxiv_id'),('C_SECTIONS','utils.py',255,298,'search_section_by_arxiv_id'),('C_ID','utils.py',305,351,'search_paper_by_arxiv_id'),('C_TITLE','utils.py',658,680,'search_paper_by_title'),('C_METRICS','metrics.py',29,49,'offline action/score aggregation'),('C_RECIPE','README.md',205,248,'Crawler PPO command'),('T_DATA','custom_agent/agent_dataset.py',5,42,'prompts and AgentDataset.__init__',True),('T_VM','custom_agent/utils.py',47,87,'gen_value_model_prompt/call_vm',True),('T_STUB','custom_agent/utils.py',116,118,'call_selector',True),('T_ACTION','custom_agent/utils.py',138,183,'response_handler action parsing',True),('T_REWARD','custom_agent/utils.py',185,249,'response_handler rewards/dedup/stop',True),('T_NEXT','custom_agent/utils.py',255,330,'rollout and next-session construction',True),('T_LOOP','trl/trainer/ppo_trainer.py',366,423,'PPOTrainer.train generation then rollout',True),('T_LOSS','trl/trainer/ppo_trainer.py',517,542,'KL/GAE rewards',True),('T_CONFIG','trl/trainer/ppo_config.py',53,76,'PPOConfig defaults',True)]:code(*v)
rows=[]
def row(id,aspect,status,paper,training,inference,discrepancy,evidence,uncertainty=''):
 rows.append(dict(id=id,aspect=aspect,status=status,paper_definition=paper,checkpoint_training_evidence=training,current_inference=inference,discrepancy=discrepancy,evidence_ids=evidence,uncertainty=uncertainty))
row('state','state representation','PARTIAL','形式状态=当前 LLM context + paper queue；Sq 为 query-only，Sq+p 为 query+当前论文元信息。并未明确整个 queue 被序列化成 token。','公开训练 prompt 为 query-only 或 query+title+abstract+section names；结果论文用于下一 session。','Python 保存 queue/touch_ids/score/树；Crawler 输入只有 query 或 query+单篇论文元信息，无队列全集、分数、剩余预算。','环境 state 与模型可见 observation 不等价；不能把 Python 内存在的数据算成 Crawler 看见的数据。',['P_STATE','P_RETURN','T_DATA','T_NEXT','C_INIT','C_CONTEXT','C_PROMPT'])
row('actions','action space','PARTIAL','token-level action 是词表；工具层函数为 Search、Expand、Stop。','按外部 typ 只解析 Search 或 Expand；StopSearch/StopExpand 被 reward handler 识别。','Search 阶段只提取 Search 文本；Expand 阶段只提取 Expand 文本；没有统一三动作 dispatcher。','声明的函数接口比实际可执行接口宽；标记也不是单独新增 special token 的证据。',['P_STATE','P_FUN','T_ACTION','T_REWARD','C_INIT','C_SEARCH','C_DOEXP'])
row('search_decision','Search 决策','PARTIAL','根据当前 context 生成 query 调用 Search；训练协议从 Sq 开始。','先产生整个 Search session，再 rollout；正常路径随后只构造 Expand session。','run 固定先且仅调用一次 search；模型决定 query 文本及可解析数量，不能在 Expand 后重启 Search。','阶段调度由 Python 决定；论文方法层未明确禁止回搜，但训练描述不支持宣称已学会回搜。',['P_FUN','P_SFT','T_LOOP','C_RUN','C_SEARCH'])
row('query_generation','query generation','MATCH','Search session 是多条互补 query 的序列；偏好 survey 是公开 prompt 的一部分。','GPT-4o 合成 query 列表再串接 Search 标记；公开训练 prompt 与当前 prompt 同型。','一次 infer 自回归生成多个 query，regex 后取至多 search_queries=5；尚无外部检索反馈。','MATCH 仅指多 query session 生成；不表示 query 质量、固定五条或工具交互能力一致。',['P_SFT','T_DATA','C_SEARCH','C_INFER','C_PROMPT'])
row('feedback','retrieval feedback','PARTIAL','结果入 queue，下一 paper session 的输入依赖检索结果；同一 Search session 是否注入逐次结果未明确。','batch_generation 先完成，rollout 后执行 Search；下一轮看到新论文元信息而非上一页完整 SERP。','Search 结果转成论文对象；后续 Expand 看单篇 title/abstract/section keys，初始 query 生成不会被结果修订。','有跨 session 结果条件化；没有同 session 的 search→observation→requery 接口。',['P_RETURN','P_SFT','T_LOOP','T_NEXT','C_SEARCH','C_CONTEXT','C_GOOGLE'],'论文的通用 state 定义不足以证明具体 SERP observation schema。')
row('alternation','Search/Expand 是否可交替','UNCLEAR','一条任务轨迹包含 Search 和 Expand 已明确；是否支持同 session 混合或 Expand→Search→Expand 自由交替未明确。','模板分 Search/Expand 两种；正常 PPO 调度 Search→Expand→Expand。没有受反馈驱动的混合动作训练证据。','严格 Search phase→若干 Expand layers，没有回 Search 的边。','当前代码不支持自由交替是确定事实；把它命名为恢复论文已证明的交替能力则证据不足。',['P_FUN','P_SFT','P_PPO','T_LOOP','T_ACTION','C_RUN'],'UNCLEAR 指论文是否要求/实现自由交替，不是代码调用链不清楚。')
row('subsection','subsection selection','PARTIAL','模型选 subsection name；工具把该 subsection 引用论文入队。','SFT 按引用命中 GT/10% 多样性选择；公开训练按规范化章节名匹配。','模型选 keys；仅 exact section name 生效，程序展开该节引用标题，再解析、去重、评分。','保留核心选择机制；完整引用入队受元数据可用性、本地 resolver、名称匹配限制。',['P_FUN','P_SFT','T_ACTION','C_CONTEXT','C_DOEXP','C_REF','C_TITLE'])
row('queue','paper queue','PARTIAL','Search/Expand 追加结果；Stop 换下一 paper；Eq.(2) 依全局 Qt 去重。','公开 reward 的 searched_paper_set 在每次 response_handler 内新建；下一批论文由 reward/prob 排序取六条。','queue 为分层列表；以 Selector 分数排序新 frontier；第一层全取，之后最多20，指针越过未取项。','不是逐 Stop 驱动的可持续消费队列；训练局部去重也不等于论文全局 Qt。',['P_FUN','P_RETURN','T_REWARD','T_NEXT','C_EXPAND','C_NODE'])
row('stop','Stop 语义','MISSING','结束当前 session：query-only 时结束搜索 session，paper session 时结束当前 paper；context reset 到 query+下一 paper。','训练识别 StopSearch/StopExpand 并给 stop 位置奖励；不是 global Finish。','没有 Stop parser 或分支；生成由 EOS/token cap 结束，Python 固定执行后续调度；空 Expand 列表仅间接跳过该 paper。','缺失的是 Stop 的显式运行时语义，不是说模型不会输出停止标记或不能少选章节。',['P_FUN','P_RETURN','T_REWARD','C_INFER','C_BATCH','C_DOEXP','C_RUN'])
row('finish','global Finish','MATCH','未定义明确的可学习 global Finish；Stop 不等于任务完成，实践另有深度限制。','未见 global Finish 动作或模型输入的总预算；训练以 rounds/长度等外部界限截止。','run 在固定 layers 迭代后返回；模型无整体结束任务动作。','共同缺席（MATCH_ABSENCE）；不能作为已有 Finish 的恢复。',['P_FUN','P_SETUP','P_PPO','T_LOOP','T_CONFIG','C_RUN'],'论文对 queue 耗尽等所有边界情况没有完整状态机规格。')
row('budget','budget awareness','PARTIAL','cost 是优化目标中的软惩罚；§5.2 有外部探索深度上限，不等于显式剩余预算状态。','rounds、max_action、response_length 等外部限制；未见面向模型的 global budget 字段。','search_queries/search_papers/expand_layers/expand_papers/max_new_tokens 是外部上限，没有预算 observation。','两侧均有资源限制，均不能据此声称 budget-aware policy；运行时预算感知是未见于这些证据的新机制。',['P_REWARD','P_SETUP','P_PPO','T_ACTION','T_LOOP','T_CONFIG','C_INIT','C_INFER'])
row('cost','action cost','PARTIAL','r=α·新增相关论文数−c；Search/Expand=0.1，Stop=0；附录 G.2 验证降低无效动作。','README 覆盖参数匹配论文；公开 handler 又含截断、+cost stop shaping、局部去重和 Selector stub。','不在线计算 cost 或 reward；训练影响可能保留在输出中；metrics.py 的−0.1是离线统计。','无运行时 cost 不是 RL policy 失效的证据；公开训练 reward 不是论文公式的逐项等价实现。',['P_REWARD','P_PPO','P_COST','T_REWARD','T_STUB','C_RECIPE','C_METRICS'])
row('feedback_loop','multi-step feedback loop','PARTIAL','通过新论文 session 连续探索引用网络；跨 session value 为长期信用分配。','有下一轮 paper-context 条件化；无 session 内执行一步再生成一步的外部反馈。','后层 prompt 依赖前层找到的论文，所以不是完全无反馈；反馈仅在固定分层的论文元信息上。','不能称当前 PaSa 完全没有 multi-step；缺少的是统一、可变调度的逐工具反馈闭环。',['P_RETURN','T_LOOP','T_NEXT','C_CONTEXT','C_EXPAND','C_RUN'])
row('trajectory','trajectory execution','PARTIAL','概念上 token MDP + session 分割；展示模板为同类动作串。','先 generate 整串再解析执行，与推理批量阶段具有结构相似性。','两处 generate 都先返回整串，后执行匹配动作；不按文本中的 Search/Expand/Stop 全局顺序解释。','概念 token action 执行叙述与实现 generate-then-execute 不等价；也不能把阶段化全部归咎于当前本地补丁。',['P_STATE','P_FUN','P_SFT','T_LOOP','C_SEARCH','C_DOEXP','C_INFER'])
row('autonomy','inference-time policy autonomy','PARTIAL','模型决定查询与章节，并通过 RL 优化发现相关论文；论文的广义自主描述不能代替具体控制协议。','支持两类 session 技能和跨 session value 学习；精确 checkpoint 的任意混合/预算/重查询能力未经证明。','自主部分=生成 query/选章节/输出数量；调度类型、队列排序、深度、截止、TopK、工具与 Page1 由代码决定。','局部策略自主存在，整体调度自主受限。',['P_FUN','P_SFT','P_RETURN','T_LOOP','C_RUN','C_EXPAND','C_GOOGLE'])
row('long_term','cross-session long-term value','PARTIAL','Eq.(3) 已把新论文的下一 session 估值加入 return，允许经不直接相关论文寻找后续相关文献。','call_vm 估计论文 prompt 的值，handler 加 gamma1·value；训练代码的采样/截断另有限制。','只加载 Crawler/Selector；queue 按 Selector 当前相关性排序，不在推理时调用 value head。','长期价值学习本身已属 PaSa；运行时显式长期价值调度并非当前实现，也不能宣称模型完全没有长期倾向。',['P_RETURN','P_FUN','T_VM','T_REWARD','C_ENTRY','C_EXPAND','C_NODE'])
row('paper_input','paper body / sections / references observation','PARTIAL','可读论文的具体 session 输入列为 title+abstract+outline；不应把抽象 read papers 解释为完整正文进 LLM。','模板与公开 gen_value_model_prompt 仅含元信息和 section names。','正文由工具解析成 section→reference titles；Crawler 只收到 keys，不收到正文或引用列表。','工具访问全文与模型阅读全文是两回事；这点不是已证明的论文实现缺失。',['P_FUN','P_SFT','T_DATA','T_VM','C_CONTEXT','C_SECTIONS','C_NODE'])
row('selector','Selector / reward versus inference scoring','PARTIAL','训练时辅助相关性 reward；推理时判断相关，§4.3 允许单 token 概率用于排序。','公开 call_selector 为待部署占位；仅从 release 不能重建生产训练的服务结果。','计算 True token 全词表 softmax 概率，以>0.5筛选；结果入队不要求通过阈值；score只影响排序，不作为 Crawler prompt。','实际推理只算一个 token，不生成解释；Selector 分数和 Crawler 可见反馈须区分。',['P_RETURN','P_SETUP','T_STUB','C_SELECTOR','C_SEARCH_PAPER','C_DOEXP','C_EXPAND'])
out={'audit':'PASA_CRAWLER_MECHANISM_AUDIT_001','scope':'Static analysis only; no model execution, training or new retrieval experiment.','comparison_baseline':'ACL 2025 final, public training source pinned at 7a266d8, local inference at fe89b48','status_legend':{'MATCH':'Specified narrow mechanism agrees; for global Finish, both explicitly lack that defined feature (MATCH_ABSENCE).','PARTIAL':'Core concept partly represented but observation/execution/scope differs; does not assert missing training capability.','MISSING':'Explicit runtime mechanism absent despite paper definition.','UNCLEAR':'Primary sources do not establish the claimed paper/checkpoint capability; code behavior may still be definite.'},'checkpoint_caveat':'Public recipe/source and model card do not prove exact checkpoint training provenance or behavior. Released SFT file could not be downloaded (HTTP 401).','evidence_catalog':E,'items':rows}
(ROOT/'paper_vs_code_matrix.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
lines=['| 项目 | 标记 | 论文定义 / 边界 | 训练证据 | 当前 inference | 证据 |','|---|---|---|---|---|---|']
for r in rows:
 refs=' '.join(f"[{k}]({E[k]['url']})" for k in r['evidence_ids'])
 lines.append('| '+' | '.join([r['aspect'],r['status'],r['paper_definition'],r['checkpoint_training_evidence'],r['current_inference'],refs])+' |')
(ROOT/'matrix_table.md').write_text('\n'.join(lines)+'\n')
print('Wrote',len(rows),'matrix rows and',len(E),'evidence anchors')
