from common import ROOT, read, sha

def main():
    r=read(ROOT/'results.json'); d=read(ROOT/'dataset_manifest.json'); qs=read(ROOT/'question_outcomes.json')['questions']; a=r['policies']['Native Page1']; b=r['policies']['Always Page2']
    lines=['# SCHOLARQUEST_PAGE2_OPPORTUNITY_PROBE_005','', '## 数据与冻结','',f"- 官方数据：[ScholarQuest](https://github.com/pty12345/ScholarQuest/tree/{d['source_revision']})，`datasets/ScholarQuest.jsonl`。",f"- 数据 commit：`{d['source_revision']}`；原始文件 SHA-256：`{d['source_sha256']}`。",f"- 全部 {d['source_rows']} 条均有明确 answer_arxiv_ids；从 {d['eligible_rows']} 条按原文件顺序构成的候选池，以 seed={d['sampling_seed']} 均匀无放回抽取 50 题。",f"- 抽样列表 SHA-256：`{d['sample_sha256']}`；dataset_manifest SHA-256：`{sha(ROOT/'dataset_manifest.json')}`。",f"- GT 总数：{r['total_gt']}（同题去重，不跨题去重），只使用冻结 answer_arxiv_ids，不经过本地论文库、标题匹配或其他 GT 补充。",'- 数据、样本、协议和采集代码在首次生成与 Search 前冻结；没有换 seed、重抽样、筛除难题或改写 query。','', '## 采集配置','', '- 使用当前 PaSa 原始 Agent.infer、Crawler checkpoint、generate_query prompt、原 parser 与最多前 5 条限制。每题 seed=42；checkpoint sampling 配置不变；max_new_tokens=512。', '- Serper 每条 native query 连续请求 Page1 Top10、Page2 Top10；固定 before:2026-09-19 与 site:arxiv.org。全部 raw bytes（Base64）、parsed response、payload、UTC 时间、重试和 SHA-256 均保存。', '- Top10 指请求 num=10；搜索源实际返回少于 10 条或空 organic 时原样保留，不补请求、不剔除该题。', '- 未运行 Selector、Citation Expand 或 Router；未修改正式 paper_agent.py。',f"- 完成 {r['questions_complete']}/50 题；native queries={r['native_query_count']}；成功 Page1/Page2={r['successful_page1_responses']}/{r['successful_page2_responses']}；实际 HTTP attempts={r['http_attempts']}。", f"- Page1 完成到对应 Page2 开始的间隔：均值 {r['page_pair_gap_seconds']['mean']:.3f}s，最大 {r['page_pair_gap_seconds']['max']:.3f}s。",'', '## 唯一策略比较','', '| 策略 | GT found | Macro Search Recall | Micro Search Recall | 额外 Page2 logical calls |','|---|---:|---:|---:|---:|',f"| Native Page1 | {a['gt_found']}/{r['total_gt']} | {a['macro_search_recall']:.4%} | {a['micro_search_recall']:.4%} | 0 |",f"| Always Page2 | {b['gt_found']}/{r['total_gt']} | {b['macro_search_recall']:.4%} | {b['micro_search_recall']:.4%} | {r['extra_page2_calls']} |",'', f"- ΔGT：**{r['delta_gt']}**。",f"- Macro / Micro Recall 增量：{100*r['incremental_macro_search_recall']:.4f} / {100*r['incremental_micro_search_recall']:.4f} 个百分点。",f"- 至少新增 1 个 GT 的问题：**{r['questions_with_page2_gain']}/50**。",f"- 有 Page2 isolated gain 的 query：**{r['queries_with_page2_isolated_gain']}/{r['native_query_count']}**。",f"- ΔGT / extra Page2 call：**{r['delta_gt_per_extra_page2_call']:.4f}**。",'', 'Isolated gain 定义为某条 query 的 Page2 相对同题全部 Native Page1 union 的新增 GT。不同 query 的 isolated gain 可能重复，不能直接相加得到问题 gain。另存 pair-local gain（仅相对该 query Page1）；该次级定义下正 gain queries 为 '+str(r['queries_with_page2_pair_local_gain'])+'，不混用为主指标。', '', '## 搜索源遵循与解释边界','']
    for p in ['1','2']:
        s=r['source_adherence'][p]; frac=s['parseable_arxiv_fraction']
        lines.append(f"- Page{p}：organic={s['organic_results']}，原 parser 可识别 arXiv URL={s['parseable_arxiv_results']}（{frac:.2%}）；存在非匹配 URL 的 queries={s['queries_with_non_arxiv_results']}。")
    lines += ['', '这是特定样本、时间和 Google/Serper 搜索源下的 ID Search coverage，不是最终 PaSa Recall。返回结果中的非匹配 URL 不补抓取、不扩展 parser。固定日期过滤不冻结搜索索引。GT 未穷尽所有相关论文的可能性不改变冻结评分口径。', 'Always Page2 的收益只说明可用机会，不证明任何 Router 可以选择到这些 query。是否继续的探索性门槛在 Search 前固定：ΔGT≥10、至少 5 题有 gain、ΔGT/call≥0.05，同时必须 50/50 完成；它不是显著性检验。', '', '## 逐题 Page2 gain','', '| QID | 官方 query ID | native queries | GT | Page1 found | Page1+Page2 found | ΔGT |','|---|---|---:|---:|---:|---:|---:|']
    for q in qs: lines.append(f"| {q['question_id']} | {q['source_query_id']} | {q['native_query_count']} | {q['gt_count']} | {q['page1_gt_found']} | {q['page1_page2_gt_found']} | {q['delta_gt']} |")
    lines += ['', '## 产物与核验','', '- `dataset_manifest.json`：官方来源、版本、seed、50 题样本和冻结 GT。', '- `snapshot_manifest.json`：全部 generation、response、attempt 和运行记录的 hash；`responses/` 与 `attempts/` 保留原始字节。', '- `query_outcomes.json`：每条 query 的两页 ID 集、GT 命中、isolated/pair-local gain 和 response 索引。', '- `question_outcomes.json`：同题跨 query/page 去重后的结果。', '- `results.json`：仅 Native Page1 与 Always Page2 的聚合结果、机会门槛和源遵循统计。', '- `validation.json`：独立重算样本、原始响应、集合运算、指标、冻结文件及正式源码 hash 的结果。', f"- snapshot ID：`{r['snapshot_id']}`。",'', '## ScholarQuest-50 上是否存在足够明显的 Page2 opportunity，值得继续做固定 `max_jaccard top1` 的独立 routing 验证？','']
    if r['opportunity_gate_passed']:
        lines.append(f"**是。** 本次新增 {r['delta_gt']} 个 GT，分布在 {r['questions_with_page2_gain']} 题，效率为 {r['delta_gt_per_extra_page2_call']:.4f} GT/额外调用，满足搜索前冻结的三项机会门槛。值得继续独立验证固定 `max_jaccard top1`，但本实验没有实现或评估 Router，也没有证明其有效。")
    else:
        lines.append(f"**否，按搜索前冻结的门槛，本次证据不足。** 新增 {r['delta_gt']} 个 GT、{r['questions_with_page2_gain']} 题获得增益、{r['delta_gt_per_extra_page2_call']:.4f} GT/额外调用，未同时达到三项门槛；不支持据此推进固定 `max_jaccard top1` 的独立 routing 验证。这不等于 Page2 在其他样本或搜索源上没有机会。")
    (ROOT/'SCHOLARQUEST_PAGE2_OPPORTUNITY_PROBE_005.md').write_text('\n'.join(lines)+'\n')

if __name__=='__main__':main()
